import { InputEffectLibraryItem } from './input-effect.d';

export const effects: InputEffectLibraryItem[] = [{
  id: 'auto-filter',
  name: 'Auto Filter',
  parameters: [{
    id: 'filter.q',
    name: 'Filter Q',
    min: 0,
    max: 20,
    step: 0.01,
  }, {
    id: 'filter.detune',
    name: 'Filter Detune',
    min: 0,
    max: 1200,
    step: 0.1,
  }, {
    id: 'filter.frequency',
    name: 'Filter Frequency',
    min: 0,
    max: 30000,
    step: 0.1,
  }, {
    id: 'filter.gain',
    name: 'Filter Gain',
    min: 0,
    max: 30,
    step: 0.01,
  }, {
    id: 'filter.rolloff',
    name: 'Filter Rolloff',
    min: -96,
    max: -12,
    step: 12,
  }, {
    id: 'filter.type',
    name: 'Filter Type',
    min: 0,
    max: 7,
    valueMap: [
      "allpass",
      "bandpass",
      "highpass",
      "highshelf",
      "lowpass",
      "lowshelf",
      "notch",
      "peaking",
    ],
  }, {
    id: 'baseFrequency',
    name: 'Base Frequency',
    min: 0,
    max: 30000,
    step: 0.1,
  }, {
    id: 'depth',
    name: 'Depth',
    min: 0,
    max: 1,
    step: 0.01,
  }, {
    id: 'frequency',
    name: 'Frequency',
    min: 0,
    max: 30000,
    step: 0.1,
  }, {
    id: 'octaves',
    name: 'Octaves',
    min: 0,
    max: 30000,
    step: 0.1,
  }, {
    id: 'type',
    name: 'Type',
    min: 0,
    max: 3,
    valueMap: [
      'sine',
      'triangle',
      'square',
      'sawtooth',
    ],
  }, {
    id: 'wet',
    name: 'Wet',
    min: 0,
    max: 1,
    step: 0.01,
  }],
}, {
  id: 'chorus',
  name: 'Chorus',
  parameters: [{
    id: 'depth',
    name: 'Depth',
    min: 0,
    max: 1,
    step: 0.01,
  }, {
    id: 'delayTime',
    name: 'Delay',
    min: 0,
    max: 5000,
    step: 0.1,
    unit: 'ms',
  }, {
    id: 'feedback',
    name: 'Feedback',
    min: 0,
    max: 1,
    step: 0.01,
  }, {
    id: 'frequency',
    name: 'Frequency',
    min: 0,
    max: 30000,
    step: 0.1,
    unit: 'hz',
  }, {
    id: 'spread',
    name: 'Spread',
    min: 0,
    max: 360,
    step: 1,
    unit: '°',
  }, {
    id: 'wet',
    name: 'Wet',
    min: 0,
    max: 1,
    step: 0.01,
  }],
}, {
  id: 'distortion',
  name: 'Distortion',
  parameters: [{
    id: 'distortion',
    name: 'Distortion',
    min: 0,
    max: 1,
    step: 0.01,
  }, {
    id: 'wet',
    name: 'Wet',
    min: 0,
    max: 1,
    step: 0.01,
  }],
}, {
  id: 'ping-pong-delay',
  name: 'Ping Pong Delay',
  parameters: [{
    id: 'delayTime',
    name: 'Delay',
    min: 0,
    max: 60,
    step: 0.001,
    unit: 'sec',
  }, {
    id: 'feedback',
    name: 'Feedback',
    min: 0,
    max: 1,
    step: 0.01,
  }, {
    id: 'wet',
    name: 'Wet',
    min: 0,
    max: 1,
    step: 0.01,
  }]
}, {
  id: 'reverb',
  name: 'Reverb',
  parameters: [{
    id: 'decay',
    name: 'Decay',
    min: 0,
    max: 60,
    step: 0.001,
    unit: 'sec',
  }, {
    id: 'wet',
    name: 'Wet',
    min: 0,
    max: 1,
    step: 0.01,
  }],
}]
